# Generated by Django 5.2.1 on 2026-03-04 14:02

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('file', models.FileField(upload_to=projects.models.dataset_upload_path)),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('xls', 'Excel Legacy')], max_length=10)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('column_count', models.PositiveIntegerField(default=0)),
                ('schema_json', models.JSONField(blank=True, default=dict)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
