# Generated by Django 5.2.1 on 2026-03-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('dataset_profile', models.JSONField(blank=True, default=dict)),
                ('llm_feature_plan', models.JSONField(blank=True, default=dict)),
                ('applied_transformations', models.JSONField(blank=True, default=dict)),
                ('processed_columns', models.JSONField(blank=True, default=list)),
                ('transformed_file', models.FileField(blank=True, null=True, upload_to='processed/')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MLModelRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('linear_regression', 'Linear Regression'), ('logistic_regression', 'Logistic Regression'), ('random_forest', 'Random Forest'), ('svm', 'SVM')], max_length=40)),
                ('target_column', models.CharField(max_length=180)),
                ('feature_columns', models.JSONField(default=list)),
                ('metrics_json', models.JSONField(default=dict)),
                ('confusion_matrix_json', models.JSONField(blank=True, default=list)),
                ('roc_curve_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Visualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('chart_type', models.CharField(max_length=50)),
                ('spec_json', models.JSONField(default=dict)),
                ('html_snippet', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
