# Generated by Django 5.2.1 on 2026-03-04 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics_engine', '0002_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mlmodelrun',
            name='analysis_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_runs', to='analytics_engine.analysisrun'),
        ),
        migrations.AddField(
            model_name='mlmodelrun',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_runs', to='projects.dataset'),
        ),
        migrations.AddField(
            model_name='mlmodelrun',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visualization',
            name='analysis_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizations', to='analytics_engine.analysisrun'),
        ),
        migrations.AddField(
            model_name='visualization',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizations', to='projects.dataset'),
        ),
        migrations.AddField(
            model_name='visualization',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizations', to=settings.AUTH_USER_MODEL),
        ),
    ]
